// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  marketId: __t.u32(),
  symbol: __t.string(),
  baseAsset: __t.string(),
  quoteAsset: __t.string(),
  assetClass: __t.string(),
  precision: __t.u8(),
  spreadBps: __t.f64(),
  changeRate: __t.f64(),
  quoteIntervalMs: __t.u32(),
};
