// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BootstrapExternalMarketReducer from "./bootstrap_external_market_reducer";
import CancelOrderReducer from "./cancel_order_reducer";
import CloseMarketPositionReducer from "./close_market_position_reducer";
import CreatePriceAlertReducer from "./create_price_alert_reducer";
import DeleteExternalCandlesInRangeReducer from "./delete_external_candles_in_range_reducer";
import DeleteNotificationReducer from "./delete_notification_reducer";
import DeletePriceAlertReducer from "./delete_price_alert_reducer";
import IngestExternalMarketSnapshotReducer from "./ingest_external_market_snapshot_reducer";
import MarkNotificationSeenReducer from "./mark_notification_seen_reducer";
import PlaceLimitOrderReducer from "./place_limit_order_reducer";
import PlaceMarketOrderReducer from "./place_market_order_reducer";
import ReplaceExternalOrderBookReducer from "./replace_external_order_book_reducer";
import ResetSimulationReducer from "./reset_simulation_reducer";
import SyncCurrentUserReducer from "./sync_current_user_reducer";
import UpsertExternalDayCandleReducer from "./upsert_external_day_candle_reducer";
import UpsertExternalDayCandlesReducer from "./upsert_external_day_candles_reducer";
import UpsertExternalMinuteCandleReducer from "./upsert_external_minute_candle_reducer";
import UpsertExternalMinuteCandlesReducer from "./upsert_external_minute_candles_reducer";

// Import all procedure arg schemas
import * as CurrentUserCanTradeProcedure from "./current_user_can_trade_procedure";
import * as CurrentUserExistsProcedure from "./current_user_exists_procedure";
import * as PingProcedure from "./ping_procedure";

// Import all table schema definitions
import MarketRow from "./market_table";
import MarketDayCandleRow from "./market_day_candle_table";
import MarketMinuteCandleRow from "./market_minute_candle_table";
import MarketOrderBookLevelRow from "./market_order_book_level_table";
import MarketSnapshotRow from "./market_snapshot_table";
import MyMarketOrdersRow from "./my_market_orders_table";
import MyMarketPositionStateRow from "./my_market_position_state_table";
import MyNotificationsRow from "./my_notifications_table";
import MyOpenPositionLotsRow from "./my_open_position_lots_table";
import MyPositionHistoryRow from "./my_position_history_table";
import MyPriceAlertsRow from "./my_price_alerts_table";
import MyTradingAccountStateRow from "./my_trading_account_state_table";
import PersonRow from "./person_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  market: __table({
    name: 'market',
    indexes: [
      { accessor: 'id', name: 'market_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'symbol', name: 'market_symbol_idx_btree', algorithm: 'btree', columns: [
        'symbol',
      ] },
    ],
    constraints: [
      { name: 'market_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'market_symbol_key', constraint: 'unique', columns: ['symbol'] },
    ],
  }, MarketRow),
  marketDayCandle: __table({
    name: 'market_day_candle',
    indexes: [
      { accessor: 'bucketStart', name: 'market_day_candle_bucket_start_idx_btree', algorithm: 'btree', columns: [
        'bucketStart',
      ] },
      { accessor: 'id', name: 'market_day_candle_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'market_day_candle_idx', name: 'market_day_candle_market_id_bucket_start_idx_btree', algorithm: 'btree', columns: [
        'marketId',
        'bucketStart',
      ] },
      { accessor: 'marketId', name: 'market_day_candle_market_id_idx_btree', algorithm: 'btree', columns: [
        'marketId',
      ] },
    ],
    constraints: [
      { name: 'market_day_candle_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MarketDayCandleRow),
  marketMinuteCandle: __table({
    name: 'market_minute_candle',
    indexes: [
      { accessor: 'bucketStart', name: 'market_minute_candle_bucket_start_idx_btree', algorithm: 'btree', columns: [
        'bucketStart',
      ] },
      { accessor: 'id', name: 'market_minute_candle_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'market_minute_candle_idx', name: 'market_minute_candle_market_id_bucket_start_idx_btree', algorithm: 'btree', columns: [
        'marketId',
        'bucketStart',
      ] },
      { accessor: 'marketId', name: 'market_minute_candle_market_id_idx_btree', algorithm: 'btree', columns: [
        'marketId',
      ] },
    ],
    constraints: [
      { name: 'market_minute_candle_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MarketMinuteCandleRow),
  marketOrderBookLevel: __table({
    name: 'market_order_book_level',
    indexes: [
      { accessor: 'id', name: 'market_order_book_level_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'marketId', name: 'market_order_book_level_market_id_idx_btree', algorithm: 'btree', columns: [
        'marketId',
      ] },
    ],
    constraints: [
      { name: 'market_order_book_level_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MarketOrderBookLevelRow),
  marketSnapshot: __table({
    name: 'market_snapshot',
    indexes: [
      { accessor: 'marketId', name: 'market_snapshot_market_id_idx_btree', algorithm: 'btree', columns: [
        'marketId',
      ] },
    ],
    constraints: [
      { name: 'market_snapshot_market_id_key', constraint: 'unique', columns: ['marketId'] },
    ],
  }, MarketSnapshotRow),
  person: __table({
    name: 'person',
    indexes: [
    ],
    constraints: [
    ],
  }, PersonRow),
  myMarketOrders: __table({
    name: 'my_market_orders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMarketOrdersRow),
  myMarketPositionState: __table({
    name: 'my_market_position_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMarketPositionStateRow),
  myNotifications: __table({
    name: 'my_notifications',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNotificationsRow),
  myOpenPositionLots: __table({
    name: 'my_open_position_lots',
    indexes: [
    ],
    constraints: [
    ],
  }, MyOpenPositionLotsRow),
  myPositionHistory: __table({
    name: 'my_position_history',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPositionHistoryRow),
  myPriceAlerts: __table({
    name: 'my_price_alerts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPriceAlertsRow),
  myTradingAccountState: __table({
    name: 'my_trading_account_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTradingAccountStateRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("bootstrap_external_market", BootstrapExternalMarketReducer),
  __reducerSchema("cancel_order", CancelOrderReducer),
  __reducerSchema("close_market_position", CloseMarketPositionReducer),
  __reducerSchema("create_price_alert", CreatePriceAlertReducer),
  __reducerSchema("delete_external_candles_in_range", DeleteExternalCandlesInRangeReducer),
  __reducerSchema("delete_notification", DeleteNotificationReducer),
  __reducerSchema("delete_price_alert", DeletePriceAlertReducer),
  __reducerSchema("ingest_external_market_snapshot", IngestExternalMarketSnapshotReducer),
  __reducerSchema("mark_notification_seen", MarkNotificationSeenReducer),
  __reducerSchema("place_limit_order", PlaceLimitOrderReducer),
  __reducerSchema("place_market_order", PlaceMarketOrderReducer),
  __reducerSchema("replace_external_order_book", ReplaceExternalOrderBookReducer),
  __reducerSchema("reset_simulation", ResetSimulationReducer),
  __reducerSchema("sync_current_user", SyncCurrentUserReducer),
  __reducerSchema("upsert_external_day_candle", UpsertExternalDayCandleReducer),
  __reducerSchema("upsert_external_day_candles", UpsertExternalDayCandlesReducer),
  __reducerSchema("upsert_external_minute_candle", UpsertExternalMinuteCandleReducer),
  __reducerSchema("upsert_external_minute_candles", UpsertExternalMinuteCandlesReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("current_user_can_trade", CurrentUserCanTradeProcedure.params, CurrentUserCanTradeProcedure.returnType),
  __procedureSchema("current_user_exists", CurrentUserExistsProcedure.params, CurrentUserExistsProcedure.returnType),
  __procedureSchema("ping", PingProcedure.params, PingProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

