// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  marketId: __t.u32(),
  price: __t.f64(),
  open24H: __t.f64(),
  high24H: __t.f64(),
  low24H: __t.f64(),
  change24H: __t.f64(),
  volume24H: __t.f64(),
  updatedAtMillis: __t.u64(),
};
