// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  marketId: __t.u32().primaryKey().name("market_id"),
  price: __t.f64(),
  open24H: __t.f64().name("open_24_h"),
  high24H: __t.f64().name("high_24_h"),
  low24H: __t.f64().name("low_24_h"),
  change24H: __t.f64().name("change_24_h"),
  volume24H: __t.f64().name("volume_24_h"),
  updatedAt: __t.timestamp().name("updated_at"),
});
