// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  marketId: __t.u32().name("market_id"),
  isBid: __t.bool().name("is_bid"),
  level: __t.u8(),
  price: __t.f64(),
  size: __t.f64(),
  updatedAt: __t.timestamp().name("updated_at"),
});
