// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  marketId: __t.u32().name("market_id"),
  side: __t.string(),
  orderType: __t.string().name("order_type"),
  status: __t.string(),
  quantity: __t.f64(),
  limitPrice: __t.option(__t.f64()).name("limit_price"),
  filledPrice: __t.option(__t.f64()).name("filled_price"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  filledAt: __t.option(__t.timestamp()).name("filled_at"),
});
