// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  marketId: __t.u32().name("market_id"),
  quantity: __t.f64(),
  reservedQuantity: __t.f64().name("reserved_quantity"),
  availableQuantity: __t.f64().name("available_quantity"),
  averageEntryPrice: __t.f64().name("average_entry_price"),
  markPrice: __t.f64().name("mark_price"),
  marketValue: __t.f64().name("market_value"),
  unrealizedPnl: __t.f64().name("unrealized_pnl"),
  updatedAt: __t.timestamp().name("updated_at"),
});
