// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  auth0UserId: __t.string().name("auth_0_user_id"),
  kind: __t.string(),
  level: __t.string(),
  title: __t.string(),
  message: __t.string(),
  marketId: __t.option(__t.u32()).name("market_id"),
  createdAt: __t.timestamp().name("created_at"),
});
