// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  auth0UserId: __t.string().name("auth_0_user_id"),
  marketId: __t.u32().name("market_id"),
  triggerPrice: __t.f64().name("trigger_price"),
  referencePriceKind: __t.string().name("reference_price_kind"),
  triggerDirection: __t.string().name("trigger_direction"),
  status: __t.string(),
  expiresAt: __t.timestamp().name("expires_at"),
  triggeredAt: __t.option(__t.timestamp()).name("triggered_at"),
  triggeredPrice: __t.option(__t.f64()).name("triggered_price"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
