// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  orderId: __t.u64().name("order_id"),
  auth0UserId: __t.string().name("auth_0_user_id"),
  marketId: __t.u32().name("market_id"),
  quantity: __t.f64(),
  entryPrice: __t.f64().name("entry_price"),
  exitPrice: __t.f64().name("exit_price"),
  realizedPnl: __t.f64().name("realized_pnl"),
  closedAt: __t.timestamp().name("closed_at"),
});
