// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  auth0UserId: __t.string().name("auth_0_user_id"),
  currency: __t.string(),
  balance: __t.f64(),
  reservedBalance: __t.f64().name("reserved_balance"),
  availableBalance: __t.f64().name("available_balance"),
  unrealizedPnl: __t.f64().name("unrealized_pnl"),
  netLiquidationValue: __t.f64().name("net_liquidation_value"),
  updatedAt: __t.timestamp().name("updated_at"),
});
