// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ExternalOrderBookLevelInput,
} from "./types";

export default {
  marketId: __t.u32(),
  updatedAtMillis: __t.u64(),
  get bids() {
    return __t.array(ExternalOrderBookLevelInput);
  },
  get asks() {
    return __t.array(ExternalOrderBookLevelInput);
  },
};
