// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ExternalMarketCandleInput = __t.object("ExternalMarketCandleInput", {
  marketId: __t.u32(),
  bucketStartMillis: __t.u64(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
});
export type ExternalMarketCandleInput = __Infer<typeof ExternalMarketCandleInput>;

export const ExternalOrderBookLevelInput = __t.object("ExternalOrderBookLevelInput", {
  level: __t.u8(),
  price: __t.f64(),
  size: __t.f64(),
});
export type ExternalOrderBookLevelInput = __Infer<typeof ExternalOrderBookLevelInput>;

export const Market = __t.object("Market", {
  id: __t.u32(),
  symbol: __t.string(),
  baseAsset: __t.string(),
  quoteAsset: __t.string(),
  assetClass: __t.string(),
  spreadBps: __t.f64(),
  changeRate: __t.f64(),
  quoteIntervalMs: __t.u32(),
  precision: __t.u8(),
});
export type Market = __Infer<typeof Market>;

export const MarketDayCandle = __t.object("MarketDayCandle", {
  id: __t.u64(),
  marketId: __t.u32(),
  bucketStart: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
});
export type MarketDayCandle = __Infer<typeof MarketDayCandle>;

export const MarketMinuteCandle = __t.object("MarketMinuteCandle", {
  id: __t.u64(),
  marketId: __t.u32(),
  bucketStart: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
});
export type MarketMinuteCandle = __Infer<typeof MarketMinuteCandle>;

export const MarketOrderBookLevel = __t.object("MarketOrderBookLevel", {
  id: __t.u64(),
  marketId: __t.u32(),
  isBid: __t.bool(),
  level: __t.u8(),
  price: __t.f64(),
  size: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketOrderBookLevel = __Infer<typeof MarketOrderBookLevel>;

export const MarketOrderState = __t.object("MarketOrderState", {
  id: __t.u64(),
  marketId: __t.u32(),
  side: __t.string(),
  executionType: __t.string(),
  orderType: __t.string(),
  status: __t.string(),
  quantity: __t.f64(),
  limitPrice: __t.option(__t.f64()),
  filledPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  filledAt: __t.option(__t.timestamp()),
});
export type MarketOrderState = __Infer<typeof MarketOrderState>;

export const MarketPositionState = __t.object("MarketPositionState", {
  marketId: __t.u32(),
  side: __t.string(),
  quantity: __t.f64(),
  reservedQuantity: __t.f64(),
  availableQuantity: __t.f64(),
  averageEntryPrice: __t.f64(),
  markPrice: __t.f64(),
  marketValue: __t.f64(),
  unrealizedPnl: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketPositionState = __Infer<typeof MarketPositionState>;

export const MarketSnapshot = __t.object("MarketSnapshot", {
  marketId: __t.u32(),
  price: __t.f64(),
  open24H: __t.f64(),
  high24H: __t.f64(),
  low24H: __t.f64(),
  change24H: __t.f64(),
  volume24H: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketSnapshot = __Infer<typeof MarketSnapshot>;

export const MarketState = __t.object("MarketState", {
  marketId: __t.u32(),
  seed: __t.u64(),
  tick: __t.u32(),
  minuteCandleId: __t.u64(),
  minuteBucketStart: __t.timestamp(),
  minuteOpen: __t.f64(),
  minuteHigh: __t.f64(),
  minuteLow: __t.f64(),
  minuteClose: __t.f64(),
  minuteVolume: __t.f64(),
  dayCandleId: __t.u64(),
  dayBucketStart: __t.timestamp(),
  dayOpen: __t.f64(),
  dayHigh: __t.f64(),
  dayLow: __t.f64(),
  dayClose: __t.f64(),
  dayVolume: __t.f64(),
});
export type MarketState = __Infer<typeof MarketState>;

export const MarketTickSchedule = __t.object("MarketTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  tickIntervalMs: __t.u32(),
});
export type MarketTickSchedule = __Infer<typeof MarketTickSchedule>;

export const MyMarketOrders = __t.object("MyMarketOrders", {});
export type MyMarketOrders = __Infer<typeof MyMarketOrders>;

export const MyMarketPositionState = __t.object("MyMarketPositionState", {});
export type MyMarketPositionState = __Infer<typeof MyMarketPositionState>;

export const MyNotifications = __t.object("MyNotifications", {});
export type MyNotifications = __Infer<typeof MyNotifications>;

export const MyOpenPositionLots = __t.object("MyOpenPositionLots", {});
export type MyOpenPositionLots = __Infer<typeof MyOpenPositionLots>;

export const MyPositionHistory = __t.object("MyPositionHistory", {});
export type MyPositionHistory = __Infer<typeof MyPositionHistory>;

export const MyPriceAlerts = __t.object("MyPriceAlerts", {});
export type MyPriceAlerts = __Infer<typeof MyPriceAlerts>;

export const MyTradingAccountState = __t.object("MyTradingAccountState", {});
export type MyTradingAccountState = __Infer<typeof MyTradingAccountState>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  kind: __t.string(),
  level: __t.string(),
  title: __t.string(),
  message: __t.string(),
  marketId: __t.option(__t.u32()),
  seen: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const NotificationState = __t.object("NotificationState", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  kind: __t.string(),
  level: __t.string(),
  title: __t.string(),
  message: __t.string(),
  marketId: __t.option(__t.u32()),
  seen: __t.bool(),
  createdAt: __t.timestamp(),
});
export type NotificationState = __Infer<typeof NotificationState>;

export const OpenPositionLotState = __t.object("OpenPositionLotState", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  side: __t.string(),
  quantity: __t.f64(),
  openPrice: __t.f64(),
  currentPrice: __t.f64(),
  unrealizedPnl: __t.f64(),
  openedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type OpenPositionLotState = __Infer<typeof OpenPositionLotState>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const PositionHistory = __t.object("PositionHistory", {
  id: __t.u64(),
  orderId: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  quantity: __t.f64(),
  entryPrice: __t.f64(),
  exitPrice: __t.f64(),
  realizedPnl: __t.f64(),
  closedAt: __t.timestamp(),
});
export type PositionHistory = __Infer<typeof PositionHistory>;

export const PositionHistoryState = __t.object("PositionHistoryState", {
  id: __t.u64(),
  orderId: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  quantity: __t.f64(),
  entryPrice: __t.f64(),
  exitPrice: __t.f64(),
  realizedPnl: __t.f64(),
  closedAt: __t.timestamp(),
});
export type PositionHistoryState = __Infer<typeof PositionHistoryState>;

export const PriceAlert = __t.object("PriceAlert", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  triggerPrice: __t.f64(),
  referencePriceKind: __t.string(),
  triggerDirection: __t.string(),
  status: __t.string(),
  expiresAt: __t.timestamp(),
  triggeredAt: __t.option(__t.timestamp()),
  triggeredPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PriceAlert = __Infer<typeof PriceAlert>;

export const PriceAlertState = __t.object("PriceAlertState", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  triggerPrice: __t.f64(),
  referencePriceKind: __t.string(),
  triggerDirection: __t.string(),
  status: __t.string(),
  expiresAt: __t.timestamp(),
  triggeredAt: __t.option(__t.timestamp()),
  triggeredPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PriceAlertState = __Infer<typeof PriceAlertState>;

export const SimulatorState = __t.object("SimulatorState", {
  id: __t.u8(),
  nextCandleId: __t.u64(),
});
export type SimulatorState = __Infer<typeof SimulatorState>;

export const TradeOrder = __t.object("TradeOrder", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  side: __t.string(),
  executionType: __t.string(),
  orderType: __t.string(),
  status: __t.string(),
  quantity: __t.f64(),
  limitPrice: __t.option(__t.f64()),
  filledPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  filledAt: __t.option(__t.timestamp()),
});
export type TradeOrder = __Infer<typeof TradeOrder>;

export const TradingAccount = __t.object("TradingAccount", {
  auth0UserId: __t.string(),
  currency: __t.string(),
  balance: __t.f64(),
  accountLeverage: __t.u16(),
  reservedBalance: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingAccount = __Infer<typeof TradingAccount>;

export const TradingAccountState = __t.object("TradingAccountState", {
  auth0UserId: __t.string(),
  currency: __t.string(),
  balance: __t.f64(),
  equity: __t.f64(),
  margin: __t.f64(),
  freeMargin: __t.f64(),
  marginLevel: __t.f64(),
  accountLeverage: __t.u16(),
  reservedBalance: __t.f64(),
  availableBalance: __t.f64(),
  unrealizedPnl: __t.f64(),
  netLiquidationValue: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingAccountState = __Infer<typeof TradingAccountState>;

export const TradingPosition = __t.object("TradingPosition", {
  id: __t.string(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  side: __t.string(),
  quantity: __t.f64(),
  reservedQuantity: __t.f64(),
  averageEntryPrice: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingPosition = __Infer<typeof TradingPosition>;

export const TradingPositionLot = __t.object("TradingPositionLot", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  side: __t.string(),
  quantity: __t.f64(),
  openPrice: __t.f64(),
  openedAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type TradingPositionLot = __Infer<typeof TradingPositionLot>;

export const UserProfile = __t.object("UserProfile", {
  auth0UserId: __t.string(),
  senderIdentity: __t.identity(),
  displayName: __t.string(),
  email: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

