// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Market = __t.object("Market", {
  id: __t.u32(),
  symbol: __t.string(),
  baseAsset: __t.string(),
  quoteAsset: __t.string(),
  assetClass: __t.string(),
  spreadBps: __t.f64(),
  changeRate: __t.f64(),
  quoteIntervalMs: __t.u32(),
  precision: __t.u8(),
});
export type Market = __Infer<typeof Market>;

export const MarketDayCandle = __t.object("MarketDayCandle", {
  id: __t.u64(),
  marketId: __t.u32(),
  bucketStart: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
});
export type MarketDayCandle = __Infer<typeof MarketDayCandle>;

export const MarketMinuteCandle = __t.object("MarketMinuteCandle", {
  id: __t.u64(),
  marketId: __t.u32(),
  bucketStart: __t.timestamp(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
});
export type MarketMinuteCandle = __Infer<typeof MarketMinuteCandle>;

export const MarketOrderBookLevel = __t.object("MarketOrderBookLevel", {
  id: __t.u64(),
  marketId: __t.u32(),
  isBid: __t.bool(),
  level: __t.u8(),
  price: __t.f64(),
  size: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketOrderBookLevel = __Infer<typeof MarketOrderBookLevel>;

export const MarketOrderState = __t.object("MarketOrderState", {
  id: __t.u64(),
  marketId: __t.u32(),
  side: __t.string(),
  orderType: __t.string(),
  status: __t.string(),
  quantity: __t.f64(),
  limitPrice: __t.option(__t.f64()),
  filledPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  filledAt: __t.option(__t.timestamp()),
});
export type MarketOrderState = __Infer<typeof MarketOrderState>;

export const MarketPositionState = __t.object("MarketPositionState", {
  marketId: __t.u32(),
  quantity: __t.f64(),
  reservedQuantity: __t.f64(),
  availableQuantity: __t.f64(),
  averageEntryPrice: __t.f64(),
  markPrice: __t.f64(),
  marketValue: __t.f64(),
  unrealizedPnl: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketPositionState = __Infer<typeof MarketPositionState>;

export const MarketSnapshot = __t.object("MarketSnapshot", {
  marketId: __t.u32(),
  price: __t.f64(),
  open24H: __t.f64(),
  high24H: __t.f64(),
  low24H: __t.f64(),
  change24H: __t.f64(),
  volume24H: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type MarketSnapshot = __Infer<typeof MarketSnapshot>;

export const MarketState = __t.object("MarketState", {
  marketId: __t.u32(),
  seed: __t.u64(),
  tick: __t.u32(),
  minuteCandleId: __t.u64(),
  minuteBucketStart: __t.timestamp(),
  minuteOpen: __t.f64(),
  minuteHigh: __t.f64(),
  minuteLow: __t.f64(),
  minuteClose: __t.f64(),
  minuteVolume: __t.f64(),
  dayCandleId: __t.u64(),
  dayBucketStart: __t.timestamp(),
  dayOpen: __t.f64(),
  dayHigh: __t.f64(),
  dayLow: __t.f64(),
  dayClose: __t.f64(),
  dayVolume: __t.f64(),
});
export type MarketState = __Infer<typeof MarketState>;

export const MarketTickSchedule = __t.object("MarketTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  tickIntervalMs: __t.u32(),
});
export type MarketTickSchedule = __Infer<typeof MarketTickSchedule>;

export const MyMarketOrders = __t.object("MyMarketOrders", {});
export type MyMarketOrders = __Infer<typeof MyMarketOrders>;

export const MyMarketPositionState = __t.object("MyMarketPositionState", {});
export type MyMarketPositionState = __Infer<typeof MyMarketPositionState>;

export const MyTradingAccountState = __t.object("MyTradingAccountState", {});
export type MyTradingAccountState = __Infer<typeof MyTradingAccountState>;

export const Person = __t.object("Person", {
  name: __t.string(),
});
export type Person = __Infer<typeof Person>;

export const SimulatorState = __t.object("SimulatorState", {
  id: __t.u8(),
  nextCandleId: __t.u64(),
});
export type SimulatorState = __Infer<typeof SimulatorState>;

export const TradeOrder = __t.object("TradeOrder", {
  id: __t.u64(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  side: __t.string(),
  orderType: __t.string(),
  status: __t.string(),
  quantity: __t.f64(),
  limitPrice: __t.option(__t.f64()),
  filledPrice: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  filledAt: __t.option(__t.timestamp()),
});
export type TradeOrder = __Infer<typeof TradeOrder>;

export const TradingAccount = __t.object("TradingAccount", {
  auth0UserId: __t.string(),
  currency: __t.string(),
  balance: __t.f64(),
  reservedBalance: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingAccount = __Infer<typeof TradingAccount>;

export const TradingAccountState = __t.object("TradingAccountState", {
  auth0UserId: __t.string(),
  currency: __t.string(),
  balance: __t.f64(),
  reservedBalance: __t.f64(),
  availableBalance: __t.f64(),
  unrealizedPnl: __t.f64(),
  netLiquidationValue: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingAccountState = __Infer<typeof TradingAccountState>;

export const TradingPosition = __t.object("TradingPosition", {
  id: __t.string(),
  auth0UserId: __t.string(),
  marketId: __t.u32(),
  quantity: __t.f64(),
  reservedQuantity: __t.f64(),
  averageEntryPrice: __t.f64(),
  updatedAt: __t.timestamp(),
});
export type TradingPosition = __Infer<typeof TradingPosition>;

export const UserProfile = __t.object("UserProfile", {
  auth0UserId: __t.string(),
  senderIdentity: __t.identity(),
  displayName: __t.string(),
  email: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

