// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  marketId: __t.u32(),
  bucketStartMillis: __t.u64(),
  open: __t.f64(),
  high: __t.f64(),
  low: __t.f64(),
  close: __t.f64(),
  volume: __t.f64(),
};
